apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: naisd
  namespace: kube-system
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: {{ .Values.targetAverageUtilization }}
    type: Resource
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: naisd