apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: naisd
  name: naisd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: naisd
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: naisd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"