apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: naisd
spec:
  rules:
  - host: daemon.nais.devillo.no
    http:
      paths:
      - path: /
        backend:
          serviceName: naisd
          servicePort: 80
