apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: naisd
  namespace: kube-system
spec:
  rules:
  - host: "{{ .Values.ingress }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: naisd
          servicePort: 80