apiVersion: v1
kind: Service
metadata:
  name: naisd
  namespace: kube-system
  labels:
    name: naisd
spec:
  type: ClusterIP
  selector:
    app: naisd
  ports:
    - port: 80
      targetPort: 8081
