apiVersion: v1
kind: Service
metadata:
  labels:
    name: naisd
  name: naisd
  namespace: nais
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: naisd
  sessionAffinity: None
  type: {{ if .exposeService }} LoadBalancer {{ else }} ClusterIP {{ end }}
