apiVersion: v1
kind: Service
metadata:
  name: naisd
  labels:
    name: naisd
spec:
  type: NodePort
  selector:
    app: naisd
  ports:
    # the port that this service should serve on
    - port: 8081